/* Local browser acceptance of the design prototype, not product/backend tests. */
const fs=require('fs'),path=require('path'),crypto=require('crypto'),{pathToFileURL}=require('url');
const {chromium}=require('/Users/mac/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..'),base=path.join(root,'docs/设计包');
const out=path.join(__dirname,'product-design-prototype');fs.mkdirSync(out,{recursive:true});
const report={startedAt:new Date().toISOString(),scope:'LOCAL_IN_MEMORY_DESIGN_PROTOTYPE_ONLY',browser:'Installed Google Chrome via bundled Playwright, isolated temporary browser context',checks:[],screenshots:[],pageErrors:[],productTestsRun:false};
report.prototypeSha256=crypto.createHash('sha256').update(fs.readFileSync(path.join(base,'31-完整产品交互原型.html'))).digest('hex');
function check(name,pass,actual){report.checks.push({name,pass,actual});if(!pass)console.log('FAIL',name,JSON.stringify(actual))}
function result(){report.finishedAt=new Date().toISOString();report.status=report.checks.every(c=>c.pass)&&!report.pageErrors.length?'PASS':'FAIL';fs.writeFileSync(path.join(__dirname,'product-design-prototype-check.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({status:report.status,checks:report.checks.length,failures:report.checks.filter(x=>!x.pass).length,screenshots:report.screenshots.length,pageErrors:report.pageErrors.length}));}
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'});report.browserVersion=browser.version();const p=await browser.newPage({viewport:{width:1440,height:1080}});p.on('pageerror',e=>report.pageErrors.push(e.message));const url=pathToFileURL(path.join(base,'31-完整产品交互原型.html')).href;
try{
 for(const width of [1440,1024,390]){await p.setViewportSize({width,height:1080});for(let n=1;n<=22;n++){const id='P'+String(n).padStart(2,'0');await p.goto(url+'?design=1&page='+id+(id==='P08'?'&role=knowledgeadmin':''));if(id==='P08'){await p.locator('[data-ai="knowledge-pending"]').click();await p.locator('[data-ai="source"]').click();}await p.locator('h1').waitFor();const data=await p.evaluate(()=>({h1:document.querySelector('h1').innerText,bodyWidth:document.documentElement.scrollWidth,viewport:innerWidth,page:OADesignPrototype.snapshot().page}));check(`${id} ${width}px rendered and no page overflow`,!!data.h1&&data.page===id&&data.bodyWidth<=width,data);const name=`${id}-${width}.png`;await p.screenshot({path:path.join(out,name),fullPage:false});report.screenshots.push({page:id,width,height:1080,path:'validation/product-design-prototype/'+name,scope:'viewport screenshot, not full-page interaction proof'});}}
 await p.setViewportSize({width:1440,height:1080});await p.goto(url);const roleIds=await p.locator('#role option').evaluateAll(opts=>opts.map(o=>o.value));for(const r of roleIds){await p.locator('#role').selectOption(r);const actual=await p.evaluate(()=>({role:OADesignPrototype.snapshot().role,overview:OADesignPrototype.snapshot().overview,title:document.querySelector('h1').innerText,nav:document.querySelectorAll('nav button').length}));check('role view '+r,actual.role===r&&!actual.overview&&actual.nav>0&&!!actual.title,actual)}
 await p.goto(url+'?design=1&page=P16');const scenarios=await p.evaluate(()=>OADesignPrototype.scenarios);for(const name of scenarios){await p.locator(`[data-scenario="${name}"]`).click();let total=await p.locator('[data-step]').count();for(let i=0;i<total;i++)await p.locator(`[data-step="${i}"]`).click();const snap=await p.evaluate(()=>OADesignPrototype.snapshot());const s=snap.state;const expect={happy:s.received&&!!s.committed,stale:!!s.committed&&s.baseline===s.budgetBasis&&s.history.some(x=>x.startsWith('已阻止')),transfer:s.assignee==='戊'&&!!s.committed&&s.epoch===s.runEpoch,blocked:s.received&&s.history.some(x=>x.includes('已阻止：必需预算')),unknown:!!s.committed&&s.external==='已查证：单一外部对象',market:s.copies===1&&s.connection&&s.history.some(x=>x.includes('已阻止')),rework:!!s.committed&&s.epoch===2&&s.epoch===s.runEpoch};check('guided scenario '+name,Boolean(expect[name]),snap);await p.screenshot({path:path.join(out,'scenario-'+name+'.png'),fullPage:false});report.screenshots.push({scenario:name,path:'validation/product-design-prototype/scenario-'+name+'.png'});}
 await p.goto(url+'?design=1&page=P16');await p.locator('#content [data-action="approve"]').click();let s=await p.evaluate(()=>OADesignPrototype.snapshot().state);check('self approval blocked',s.notice.includes('被指定的独立审核人')&&s.reviewVersion===null,s.notice);
 await p.goto(url+'?design=1&page=P16');await p.locator('[data-scenario="happy"]').click();for(let i=0;i<5;i++)await p.locator(`[data-step="${i}"]`).click();const before=await p.evaluate(()=>OADesignPrototype.snapshot().state.committed);await p.locator('#role').selectOption('tech');await p.locator('#overview').click();await p.locator('nav [data-page="P20"]').click();await p.locator('#content [data-action="baseline"]').click();s=await p.evaluate(()=>OADesignPrototype.snapshot().state);check('delivered package immutable',JSON.stringify(s.committed)===JSON.stringify(before)&&s.notice.includes('已交付包不可改写'),s.notice);
 await p.goto(url);await p.locator('[data-task="A"]').click();await p.locator('#draft').fill('采购A的私有草稿');await p.locator('#content [data-action="saveDraft"]').click();await p.locator('#content [data-page="P01"]').click();await p.locator('[data-task="B"]').click();check('B draft starts empty',await p.locator('#draft').inputValue()==='',await p.locator('#draft').inputValue());await p.locator('#draft').fill('采购B的私有草稿');await p.locator('#content [data-action="saveDraft"]').click();await p.locator('#content [data-page="P01"]').click();await p.locator('[data-task="A"]').click();check('A draft preserved independently',await p.locator('#draft').inputValue()==='采购A的私有草稿',await p.locator('#draft').inputValue());
 await p.goto(url+'?design=1&page=P04');await p.locator('#content [data-action="suggestConfig"]').click();await p.locator('#content [data-action="acceptConfig"]').click();s=await p.evaluate(()=>OADesignPrototype.snapshot().state);check('AI configuration preview and accept without run',s.aiConfigAccepted===true&&s.committed===null,s.notice);
 for(const [id,action,field] of [['P19','analyze','analysis'],['P08','confirmFact','factConfirmed'],['P14','proactiveDraft','proactiveDraft'],['P09','evaluateEvolution','evolutionEvaluated'],['P21','savePreference','preferenceSaved']]){await p.goto(url+'?design=1&page='+id+(id==='P08'?'&role=knowledgeadmin':''));if(id==='P08'){await p.locator('[data-ai="knowledge-pending"]').click();await p.locator('[data-ai="source"]').click();}await p.locator(`#content [data-action="${action}"]`).click();s=await p.evaluate(()=>OADesignPrototype.snapshot().state);check('AI experience '+id,s[field]===true,{notice:s.notice,[field]:s[field]});}
 await p.goto(url+'?design=1&page=P22');await p.locator('[data-market="我的复制"]').click();check('market empty state',await p.locator('#content .empty').count()===1,'no copies');
 await p.locator('[data-market="技能"]').click();check('market skill filter',await p.locator('#content .card').count()===1&&await p.locator('#content .card').innerText().then(x=>x.includes('预算核对')),'one skill');await p.locator('#content [data-action="copySkill"]').click();await p.locator('#content [data-action="copySkill"]').click();await p.locator('[data-market="数字员工"]').click();await p.locator('#content [data-action="copy"]').click();s=await p.evaluate(()=>OADesignPrototype.snapshot().state);check('copies separated by resource and idempotent',s.copies===2&&s.copiedResources.includes('技能')&&s.copiedResources.includes('数字员工'),s.copiedResources);await p.locator('[data-market="我的复制"]').click();check('my copies filter',await p.locator('#content .card').count()===2,'two adopted resources');
 await p.goto(url+'?design=1&page=P21');await p.locator('#content .form select').nth(1).selectOption({index:1});await p.locator('#content [data-action="savePreference"]').click();check('saved preference value survives rerender',await p.locator('#content .form select').nth(1).evaluate(x=>x.selectedIndex)===1,'daily digest selected');
 await p.goto(url);check('no stale-source alert in initial state',await p.locator('.stat').nth(3).locator('b').innerText()==='0','initial version consistent');await p.locator('[data-task="B"]').click();check('secondary instance excludes A delivery controls',await p.locator('#content [data-action="commit"]').count()===0&&await p.locator('#draft').count()===1,'B own draft-only design boundary');
 await p.goto(url);await p.locator('#role').selectOption('auditor');check('audit summary masks business titles',!await p.locator('#content').innerText().then(x=>x.includes('研发实验室')||x.includes('年度技术服务合同')),await p.locator('h1').innerText());check('audit view has no process start action',await p.locator('#content [data-action="newInstance"]').count()===0,'restricted entry');
}catch(e){check('unhandled browser acceptance error',false,e.stack);}finally{await browser.close();result();process.exitCode=report.status==='PASS'?0:1}})().catch(e=>{check('browser launch',false,e.stack);result();process.exitCode=1});
