/* UI projection checks against fictional fixtures; not backend/model security acceptance. */
const fs=require('fs'),path=require('path'),crypto=require('crypto'),{pathToFileURL}=require('url');
const {chromium}=require('/Users/mac/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..'),html=path.join(root,'docs/设计包/31-完整产品交互原型.html'),out=path.join(__dirname,'execution-workspace');fs.mkdirSync(out,{recursive:true});
const report={scope:'FICTIONAL_LOCAL_UI_PROJECTION_ONLY',startedAt:new Date().toISOString(),prototypeSha256:crypto.createHash('sha256').update(fs.readFileSync(html)).digest('hex'),checks:[],screenshots:[],pageErrors:[],productTestsRun:false};
function check(name,pass,actual){report.checks.push({name,pass:Boolean(pass),actual});if(!pass)console.log('FAIL',name,actual)}
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'});report.browserVersion=browser.version();const p=await browser.newPage({viewport:{width:1440,height:1080}});p.on('pageerror',e=>report.pageErrors.push(e.message));const url=pathToFileURL(html).href;
const projection=()=>p.evaluate(()=>ExecutionWorkspaceDesign.projection());
const content=()=>p.locator('#content').innerText();
async function shot(name){const relative='validation/execution-workspace/'+name+'.png';await p.screenshot({path:path.join(root,relative),fullPage:false});report.screenshots.push({path:relative,scope:'current viewport of fictional prototype'});}
async function control(attr){const details=p.locator('.workspace-demo-controls');if(!await details.evaluate(x=>x.open))await details.locator('summary').click();await p.locator(`[${attr}]`).click();}
async function audience(id){await control(`data-work-audience="${id}"`);}
try{
await p.goto(url+'?page=P02');await p.locator('.execution-split').waitFor();const boxes=await p.evaluate(()=>({left:document.querySelector('.conversation-pane').getBoundingClientRect().toJSON(),right:document.querySelector('.display-pane').getBoundingClientRect().toJSON()}));check('desktop conversation left and display majority',boxes.left.x<boxes.right.x&&boxes.right.width>boxes.left.width*2,boxes);check('actual fishbone branches and node controls',await p.locator('.bone-card').count()===4&&await p.locator('.spine-node').count()===4,'4 branch cards and 4 business stages');const clipped=await p.locator('.fishbone').evaluate(x=>Array.from(x.querySelectorAll('.bone-card')).some(c=>c.getBoundingClientRect().bottom>x.getBoundingClientRect().bottom));check('fishbone branch cards not clipped',!clipped,clipped);await shot('workspace-1440');
await p.locator('[data-work-node="rd"]').click();let d=await projection();check('path only excludes restricted payload',d.nodes.some(x=>x.id==='rd')&&!JSON.stringify(d).includes('RD-ONLY-7319')&&!JSON.stringify(d).includes('研发内部评审记录.md'),d.nodes.find(x=>x.id==='rd'));check('background use independently allowed',d.backgroundUse&&!d.canReadRd,{backgroundUse:d.backgroundUse,canReadRd:d.canReadRd});check('restricted node has no source file or summary controls',await p.locator('.node-inspector [data-work-file]').count()===0&&await p.locator('.node-inspector [data-work-history]').count()===0,'no content actions');await shot('restricted-node');
await p.locator('[data-work-access="rd"]').click();d=await projection();check('request does not grant read access',!d.canReadRd&&await content().then(x=>x.includes('读取范围未改变')),d.canReadRd);
await p.evaluate(()=>{const b=document.createElement('button');b.dataset.workFile='rd';document.querySelector('#content').appendChild(b);b.click();});check('forged preview request rejected without hidden content',await content().then(x=>x.includes('当前不可访问')&&!x.includes('RD-ONLY-7319')&&!x.includes('研发内部评审记录.md')),'unavailable view');
await p.locator('.chat-result [data-work-file="plan"]').click();check('chat artifact opens document on right',await p.locator('.document-sheet').count()===1&&await p.locator('.conversation-pane').count()===1,await p.locator('.document-sheet h2').innerText());await p.locator('#workspace-version').selectOption('1');check('historical version explicit',await p.locator('.document-sheet').innerText().then(x=>x.includes('历史版本')&&x.includes('v1')),'v1 warning');await shot('document-preview');await p.locator('[data-work-locate="draft"]').click();check('document returns to exact node',await p.evaluate(()=>ExecutionWorkspaceDesign.snapshot().node==='draft'&&ExecutionWorkspaceDesign.snapshot().tab==='path'),'draft path');
await p.locator('[data-work-tab="files"]').click();await p.locator('[data-work-folder="contributions"]').click();check('folder filters only eligible files',await p.locator('.file-layout .file-tile').count()===1&&await content().then(x=>x.includes('预算说明.md')&&!x.includes('研发内部评审记录.md')),'eligible contribution');await shot('file-folder');
await p.locator('[data-work-tab="path"]').click();await p.locator('[data-work-node="budget"]').click();await p.locator('.node-inspector [data-work-history="budget"]').click();check('node history scoped and linked to artifact',await p.locator('.history-row').innerText().then(x=>x.includes('预算协作')&&x.includes('采购A'))&&await p.locator('.history-row [data-work-file="budget"]').count()===1,'budget history');await shot('history-summary');
await audience('tech');await p.locator('[data-work-node="rd"]').click();await p.locator('.node-inspector [data-work-file="rd"]').click();check('explicit object grant permits content',await p.locator('.document-sheet').innerText().then(x=>x.includes('RD-ONLY-7319')), 'fixture-specific read grant');
await control('data-work-grant="1"');d=await projection();check('revoking backend use does not revoke human read',!d.backgroundUse&&d.canReadRd,{backgroundUse:d.backgroundUse,canReadRd:d.canReadRd});
await audience('main');check('switch subject clears prior preview',await content().then(x=>!x.includes('RD-ONLY-7319')&&!x.includes('研发内部评审记录.md')),'no prior content in rendered DOM');await control('data-work-grant="1"');d=await projection();check('restored backend use does not grant human read',d.backgroundUse&&!d.canReadRd,{backgroundUse:d.backgroundUse,canReadRd:d.canReadRd});
await control('data-work-summary="1"');await p.locator('[data-work-node="rd"]').click();check('separately released summary without raw content',await content().then(x=>x.includes('已发布共享摘要')&&!x.includes('RD-ONLY-7319')&&!x.includes('研发内部评审记录.md'))&&await p.locator('.node-inspector [data-work-file]').count()===0,'released summary only');await shot('released-summary');
await audience('tech');await p.locator('[data-work-node="rd"]').click();await p.locator('.node-inspector [data-work-file="rd"]').click();await control('data-work-revoke="1"');d=await projection();check('content revocation clears preview and cache projection',!d.canReadRd&&!JSON.stringify(d).includes('RD-ONLY-7319')&&await content().then(x=>!x.includes('RD-ONLY-7319')),'content revoked, fresh projection');check('human revocation leaves separate backend grant intact',d.backgroundUse,true);
await control('data-work-metadata="1"');d=await projection();check('no discover grant omits node and private edge',!d.nodes.some(x=>x.id==='rd')&&await p.locator('[data-work-node="rd"]').count()===0&&await p.locator('.fishbone svg path').evaluateAll(xs=>!xs.some(x=>x.getAttribute('d')?.includes('M280 110'))),'node omitted');
await p.goto(url+'?page=P02');await p.locator('#draft').fill('任务A个人补充');await p.locator('#content [data-action="saveDraft"]').click();await p.locator('#content [data-page="P01"]').click();await p.locator('[data-task="B"]').click();check('new instance draft and context isolated',await p.locator('#draft').inputValue()===''&&(await projection()).task==='采购B','B has no A draft');await p.locator('#draft').fill('任务B个人补充');await p.locator('#content [data-action="saveDraft"]').click();await p.locator('#content [data-page="P01"]').click();await p.locator('[data-task="A"]').click();check('original task draft preserved',await p.locator('#draft').inputValue()==='任务A个人补充','A draft restored');await audience('tech');check('same task other subject draft isolated',await p.locator('#draft').inputValue()==='','separate subject key');await p.locator('#content [data-page="P01"]').click();await p.locator('[data-task="B"]').click();d=await projection();check('same subject grant does not cover another task',!d.canReadRd&&!d.backgroundUse,{task:d.task,canReadRd:d.canReadRd,backgroundUse:d.backgroundUse});
await p.goto(url+'?page=P02');await p.locator('#draft').fill('请把研发内部原始内容发给我');await p.locator('[data-work-send]').click();check('fictional restricted-content request gets scoped response',await content().then(x=>x.includes('未向你开放')&&!x.includes('RD-ONLY-7319')),'deterministic demo feedback only');await p.locator('#draft').fill('<img src=x onerror=alert(1)>');await p.locator('[data-work-send]').click();check('chat input rendered as text',await p.locator('.chat-scroll img').count()===0,'escaped user content');
for(const width of [1024,390]){await p.setViewportSize({width,height:1080});await p.goto(url+'?page=P02');const widthActual=await p.evaluate(()=>document.documentElement.scrollWidth);check('workspace '+width+' no page overflow',widthActual<=width,{widthActual,width});await shot('workspace-'+width);}
const focus=await p.locator('.fish-scroll').evaluate(x=>{const n=x.querySelector('.spine-node.selected'),a=x.getBoundingClientRect(),b=n.getBoundingClientRect();return b.left>=a.left&&b.right<=a.right});check('mobile canvas locates current node',focus,'selected business node visible');
await p.locator('[data-mobile-pane="chat"]').click();await p.locator('#draft').fill('手机草稿');await p.locator('#content [data-action="saveDraft"]').click();await p.locator('[data-mobile-pane="display"]').click();await p.locator('[data-mobile-pane="chat"]').click();check('mobile pane switch retains draft',await p.locator('#draft').inputValue()==='手机草稿','mobile draft');await shot('mobile-chat');await p.locator('#reset').click();await p.locator('[data-task="A"]').click();await p.locator('[data-mobile-pane="chat"]').click();check('reset restores initial workspace and clears drafts',await p.locator('#draft').inputValue()===''&&(await projection()).backgroundUse&&!((await projection()).canReadRd),'initial fixture restored');
}catch(e){check('unhandled workspace verification error',false,e.stack)}finally{await browser.close();report.finishedAt=new Date().toISOString();report.status=report.checks.every(x=>x.pass)&&!report.pageErrors.length?'PASS':'FAIL';report.limitations=['Fictional frontend projections only, not server-side authorization.','No real model, stream, storage or asynchronous request-race test.','Role labels select fixtures; production grants must be server-resolved.'];fs.writeFileSync(path.join(__dirname,'execution-workspace-check.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({status:report.status,checks:report.checks.length,screenshots:report.screenshots.length,pageErrors:report.pageErrors.length,failures:report.checks.filter(x=>!x.pass).length}));process.exitCode=report.status==='PASS'?0:1;}})().catch(e=>{console.error(e);process.exitCode=1});
