/* Independent observable UI checks, limited to the fictional design prototype. */
const fs=require('fs'),path=require('path'),crypto=require('crypto'),{pathToFileURL}=require('url');
const {chromium}=require('/Users/mac/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..'),html=path.join(root,'docs/设计包/31-完整产品交互原型.html'),out=path.join(__dirname,'ai-experience');fs.mkdirSync(out,{recursive:true});
const report={startedAt:new Date().toISOString(),scope:'FICTIONAL_UI_STATE_AND_RECOVERY_ONLY',prototypeSha256:crypto.createHash('sha256').update(fs.readFileSync(html)).digest('hex'),checks:[],screenshots:[],pageErrors:[],productTestsRun:false};
function check(name,pass,actual){report.checks.push({name,pass:Boolean(pass),actual});if(!pass)console.log('FAIL',name,actual)}
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});const p=await browser.newPage({viewport:{width:1440,height:1080}});p.on('pageerror',e=>report.pageErrors.push(e.message));report.browserVersion=browser.version();const url=pathToFileURL(html).href;
const open=(id,role='main')=>p.goto(url+'?design=1&page='+id+'&role='+role);const snap=()=>p.evaluate(()=>AIExperienceDesign.snapshot());const state=()=>p.evaluate(()=>OADesignPrototype.snapshot().state);const act=a=>p.locator('#content [data-ai="'+a+'"]').first().click();const base=a=>p.locator('#content [data-action="'+a+'"]').first().click();const text=()=>p.locator('#content').innerText();
async function nav(id){await p.evaluate(id=>navigate(id),id)}
async function subject(r,id){await p.locator('#role').selectOption(r);await p.locator('#overview').click();await p.locator('nav [data-page="'+id+'"]').click();}
async function shot(name){const target='validation/ai-experience/'+name+'.png';await p.screenshot({path:path.join(root,target),fullPage:false});report.screenshots.push({path:target,scope:'fictional UI viewport'});}
try{
 await open('P04');await base('suggestConfig');await p.locator('[data-ai-check="1"]').uncheck();await base('acceptConfig');let s=await snap();check('partial configuration preserves unselected field',s.config.values[0]===1&&s.config.values[1]===0,s.config);check('save does not run or approve',!(await state()).committed&&(await state()).reviewVersion===null,'business unchanged');await act('undo-config');check('configuration undo restores previous values',(await snap()).config.values.every(x=>x===0),'restored');await base('suggestConfig');await p.locator('.ai-debug summary').click();await act('config-conflict');await base('acceptConfig');s=await snap();check('conflict retains proposal and current settings',s.context.configDraft&&s.context.notice.includes('冲突')&&s.config.values[0]===0,s.context.notice);await base('suggestConfig');await base('acceptConfig');check('regenerated proposal resolves revision conflict',(await snap()).config.values[0]===1,'fresh diff');await shot('settings-diff-recovery');
 await open('P04','tech');await base('suggestConfig');check('non-owner cannot generate task mutation proposal',!(await snap()).context.configDraft&&(await snap()).context.notice.includes('无权'),'owner grant required');
 await open('P21');await act('propose-preference');await p.locator('[data-ai-check="0"]').uncheck();await act('apply-preference');s=await snap();check('personal preference applies selected daily digest',s.preferences.values[1]===1&&s.preferences.values[0]===0,s.preferences);await act('undo-preference');check('personal preference has undo',(await snap()).preferences.values[1]===0,'reverted');await p.locator('#content .form select').nth(0).selectOption({index:1});await base('savePreference');await subject('tech','P21');check('preferences isolated by subject',(await snap()).preferences.values.every(x=>x===0),'other subject defaults');await subject('main','P21');check('own manual fallback values retained',(await snap()).preferences.values[0]===1,'manual value retained');await shot('preferences');
 await open('P19');await base('analyze');check('visible records counted from state',(await snap()).context.analysis.rows.length===3,'three fixture instances');await act('drill-delivered');check('legitimate zero result retains sample and no invented rows',await p.locator('.ai-metric').nth(2).innerText().then(x=>x.startsWith('0'))&&await p.locator('[data-ai-task]').count()===0,'sample 3, delivered 0');await act('drill-all');check('chart drilldown has same rows',await p.locator('[data-ai-task]').count()===3,'three source rows');await shot('analysis-drilldown');await p.locator('[data-ai-task="B"]').click();check('drilldown opens same business instance',(await state()).selectedTask==='B'&&await p.locator('#draft').inputValue()==='','B isolated workbench');
 for(const mode of ['empty','unauthorized','timeout']){await open('P19');await p.locator('.ai-debug summary').click();await p.locator('#ai-analysis-mode').selectOption(mode);await base('analyze');s=await snap();check(mode+' has no fabricated metric',s.context.analysis.status===mode&&await p.locator('.ai-metric').count()===0,s.context.analysis);if(mode==='timeout'){await p.locator('.ai-debug summary').click();await p.locator('#ai-analysis-mode').selectOption('ready');await base('analyze');check('timeout recovery retains question',(await snap()).context.analysis.status==='ready'&&await p.locator('#ai-question').inputValue()==='哪些事项还没有交付？','retry current question');}}
 await open('P19','auditor');await base('analyze');check('management role does not gain business analytics', (await snap()).context.analysis.status==='unauthorized'&&!(await text()).includes('合同C'),'no records or hidden count');
 await open('P19');await p.locator('#ai-question').fill('成功率多少？');await base('analyze');check('material ambiguity requests clarification',(await snap()).context.analysis.status==='clarify','no automatic ambiguous metric');await p.locator('#ai-question').fill('哪些事项还没有交付？');await base('analyze');await p.evaluate(()=>{state=reduce(state,'recheck','main');render()});check('source version changes suppress old numeric answer',await p.locator('.ai-metric').count()===0&&await text().then(x=>x.includes('结果依据已变化')),'stale guarded');
 await open('P08');await act('ask-knowledge');await act('source');check('knowledge answer opens exact visible source',await p.locator('.ai-source').innerText().then(x=>x.includes('设备清单 v1')),'source v1');await act('knowledge-pending');check('ordinary employee requests review instead of confirming',await p.locator('[data-action="confirmFact"]').count()===0&&await p.locator('[data-ai="request-knowledge"]').count()===1,'separate authority');await act('request-knowledge');check('request does not widen permissions',!(await state()).factConfirmed&&(await snap()).context.notice.includes('尚未发送'),'draft only');
 await open('P08','knowledgeadmin');await act('knowledge-pending');await base('confirmFact');check('confirmation requires opening current source',!(await state()).factConfirmed&&(await snap()).context.notice.includes('先打开'),'source first');await act('source');await base('confirmFact');check('authorized source-backed assertion confirmed',(await snap()).knowledge.status==='confirmed'&&(await state()).committed===null,'no business approval');await shot('knowledge-source-confirmation');await p.evaluate(()=>{state=reduce(state,'baseline','tech');render()});await act('source');await base('confirmFact');check('new source invalidates old confirmation for reuse',(await snap()).knowledge.version===1&&(await snap()).context.notice.includes('来源已变化'),'must rederive');await act('refresh-knowledge');await base('confirmFact');check('new candidate can be checked against current source',(await snap()).knowledge.version===2&&(await snap()).knowledge.status==='confirmed','v2 checked');
 await open('P08','auditor');check('knowledge view denies ungranted source',await p.locator('.ai-source').count()===0&&await p.locator('#ai-knowledge-question').count()===0,'no source payload');
 await open('P14');await act('snooze');check('snooze removes active suggestion but keeps work',await p.locator('[data-action="proactiveDraft"]').count()===0&&(await state()).tasks.length===3,'work unchanged');await act('wake-opportunity');await base('proactiveDraft');check('proactive acceptance continues in same task draft',(await state()).proactiveDraft&&await p.locator('#draft').inputValue().then(x=>x.includes('专业贡献')),'draft prepared, not sent');const draft=await p.locator('#draft').inputValue();await nav('P14');await base('proactiveDraft');check('same event acceptance deduplicates draft',await p.locator('#draft').inputValue()===draft,'one draft fragment');await nav('P14');await base('dismissSuggestion');await nav('P01');await nav('P14');check('dismiss remains quiet across page visits',await p.locator('[data-action="proactiveDraft"]').count()===0&&(await state()).committed===null,'no closure');await p.evaluate(()=>{state=reduce(state,'baseline','tech');render()});check('new source event can create relevant new suggestion',await p.locator('[data-action="proactiveDraft"]').count()===1&&await text().then(x=>x.includes('清单版本变化')),'new version event');
 await act('preview-plan');await act('save-plan');check('saving plan does not enable it',(await snap()).plan.status==='draft','draft');await act('enable-plan');await act('pause-plan');check('pause future triggers has separate plan state',(await snap()).plan.status==='paused'&&(await state()).external==='未调用','no external action');await shot('proactive-plan');
 await open('P09');await base('evaluateEvolution');check('ordinary experience has feedback but no publishing',await p.locator('[data-ai="evo-publish"]').count()===0&&await text().then(x=>x.includes('真实业务评估尚未执行')),'no claimed lift');await act('inaccurate');check('feedback has bounded meaning',Object.values((await snap()).feedback).includes('已标记待纠正'),'not published or memorized');
 await open('P09','skill');await act('evo-publish');check('publish without evidence blocked',(await snap()).evolution.active===1&&(await snap()).context.notice.includes('已阻止'),'default v1');await base('evaluateEvolution');await act('evo-propose');await act('evo-review');check('author cannot self review',(await snap()).evolution.status==='evaluated','independent reviewer');await subject('evolution','P09');await act('evo-review');await act('evo-trial');await act('evo-publish');check('trial without receipt cannot publish',(await snap()).evolution.status==='trial'&&(await snap()).evolution.active===1,'receipt required');await act('evo-receipt');await act('evo-publish');s=await snap();check('fictional publication keeps in-flight version pinned',s.evolution.active===2&&s.evolution.pinned===1,'new default only');await shot('evolution-trial');await act('evo-rollback');check('rollback keeps evidence and in-flight snapshot',(await snap()).evolution.active===1&&(await snap()).evolution.receipt&&(await snap()).evolution.pinned===1,'history retained');
 await open('P16');await act('context-help');check('delivery assistance lists missing conditions without approving',await p.locator('.ai-help-panel').innerText().then(x=>x.includes('专业贡献'))&&(await state()).reviewVersion===null&&(await state()).committed===null,'human authority unchanged');
 for(let i=1;i<=22;i++){const id='P'+String(i).padStart(2,'0');await open(id);check(id+' single contextual assistance entry',await p.locator('[data-ai="context-help"]').count()===1,'one per current page');}
 await open('P02');await p.locator('#draft').fill('尚未点击保存的补充');await act('context-help');check('context assistance keeps in-progress task input',await p.locator('#draft').inputValue()==='尚未点击保存的补充','no draft loss');
 await open('P20');await act('context-help');await p.locator('#ai-help-draft').fill('我的依据核对要求');await act('save-help');await subject('tech','P20');await act('context-help');check('context drafts separated by user',await p.locator('#ai-help-draft').inputValue()==='','no other user draft');await subject('main','P20');await act('context-help');check('own context draft retained',await p.locator('#ai-help-draft').inputValue()==='我的依据核对要求','own draft');
 for(const id of ['P04','P08','P09','P14','P19','P21']){await p.setViewportSize({width:390,height:1080});await open(id);const w=await p.evaluate(()=>document.documentElement.scrollWidth);check(id+' mobile has no page overflow',w<=390,w);if(id==='P19'){await base('analyze');await act('drill-all');}await shot(id+'-mobile');}
}catch(e){check('unhandled AI experience validation error',false,e.stack)}finally{await browser.close();report.finishedAt=new Date().toISOString();report.status=report.checks.every(x=>x.pass)&&!report.pageErrors.length?'PASS':'FAIL';report.limitations=['No real model/NL parsing, scheduling or server authorization.','Evidence and trial receipts are explicitly fictional; no measured improvement.','No asynchronous revocation race, persistence, real data correctness or user usability acceptance.'];fs.writeFileSync(path.join(__dirname,'ai-experience-check.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({status:report.status,checks:report.checks.length,failures:report.checks.filter(x=>!x.pass).length,screenshots:report.screenshots.length,pageErrors:report.pageErrors.length}));process.exitCode=report.status==='PASS'?0:1;}})().catch(e=>{console.error(e);process.exitCode=1});
